
source 'https://github.com/East-Coast/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'BaseXGPush_Example' do
  pod 'BaseXGPush', :path => '../'
  

  target 'BaseXGPush_Tests' do
    inherit! :search_paths

    
  end
end
